# Generated by Django 5.2 on 2025-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
