# Generated by Django 5.2 on 2025-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_country_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
