# Generated by Django 5.2 on 2025-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
