# Generated by Django 5.2 on 2025-05-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
