# Generated by Django 5.2 on 2025-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_role_sellerprofile_tenantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('self-employed', 'Self Employed'), ('govt-job', 'Government Job'), ('private job', 'Private Job'), ('house wife', 'House Wife'), ('business', 'Business'), ('retired', 'Retired')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('admin', 'Administrator'), ('agent', 'Agent'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant')], default='none', max_length=20),
        ),
    ]
