# Generated by Django 5.2 on 2025-05-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
