# Generated by Django 5.2 on 2025-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userrole_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_properties', to='core.buyerprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_properties', to='core.sellerprofile'),
        ),
    ]
