# Generated by Django 5.2 on 2025-05-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_role_alter_user_options_remove_user_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name__in': ['superadmin', 'agent', 'seller', 'buyer', 'tenant', 'landlord', 'manager']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
