# Generated by Django 5.2 on 2025-05-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_property_buyer_alter_property_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_properties', to='core.buyerprofile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_properties', to='core.sellerprofile'),
        ),
    ]
