# Generated by Django 5.2 on 2025-05-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_role_permissions_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': [('can_approve_property', 'Can approve property'), ('can_feature_property', 'Can feature property'), ('can_sell_property', 'Can mark property as sold')]},
        ),
    ]
