# Generated by Django 5.2 on 2025-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
