# Generated by Django 5.2 on 2025-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
