# Generated by Django 5.2 on 2025-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_property_image_delete_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
