# Generated by Django 5.2 on 2025-05-26 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name': ['Agent', 'Buyer', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
