# Generated by Django 5.2 on 2025-05-28 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_property_agent_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='property',
            name='seller',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
