# Generated by Django 5.2 on 2025-05-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_property_buyer_remove_property_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name__in': ['Agent', 'Buyer', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=4)),
                ('place_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('hospital', 'Hospital'), ('market', 'Market'), ('park', 'Park')], max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='core.property')),
            ],
        ),
    ]
