# Generated by Django 5.2 on 2025-05-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('core', '0009_alter_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenantprofile'),
        ),
    ]
